

spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/t712?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai


    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    username: root
#    password: 8317992

mybatis-plus:
  global-config:
    db-config:
      id-type: id_worker
      capital-mode: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
